version: "3"

services: 
  database:
    image: postgres:13.0
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'DeliveryFoodDB'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  web:
    build: ./
    command: ./docker-entrypoint.sh
    volumes:
      - ./:/usr/src/app/
    
    ports: 
      - 80:80
      - 443:443
    
    depends_on: 
      - database
